Survival-Guide/src/Mvc/Models/ConfigurationModel.cs
using Mvc.Configuration;

namespace Mvc.Models
{
    public class ConfigurationModel
    {
        public AppConfiguration OptionsConfiguration { get; set; }

        public AppConfiguration SnapshotConfiguration { get; set; }

        public AppConfiguration OptionsMonitorConfiguration { get; set; }
    }
}

Survival-Guide/src/Mvc/Models/ErrorViewModel.cs
using System;

namespace Mvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Survival-Guide/src/Mvc/Models/SampleSingleton.cs
using Microsoft.Extensions.Options;
using Mvc.Configuration;

namespace Mvc.Models
{
    public class SampleSingleton
    {
        private readonly IOptionsMonitor<AppConfiguration> _configuration;

        public SampleSingleton(IOptionsMonitor<AppConfiguration> configuration)
        {
            _configuration = configuration;
        }

        public AppConfiguration Configuration => _configuration.CurrentValue;
    }
}

Survival-Guide/src/Mvc/Controllers/ConfigurationController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Mvc.Configuration;
using Mvc.Models;

namespace Mvc.Controllers
{
    public class ConfigurationController : Controller
    {
        private readonly IOptions<AppConfiguration> _configurationOptions;
        private readonly IOptionsSnapshot<AppConfiguration> _configurationSnapshot;
        private readonly SampleSingleton _singleton;

        public ConfigurationController(
            IOptions<AppConfiguration> configurationOptions,
            IOptionsSnapshot<AppConfiguration> configurationSnapshot,
            SampleSingleton singleton)
        {
            _configurationOptions = configurationOptions;
            _configurationSnapshot = configurationSnapshot;
            _singleton = singleton;
        }

        public IActionResult Index()
        {
            return View(new ConfigurationModel
            {
                OptionsConfiguration = _configurationOptions.Value,
                SnapshotConfiguration = _configurationSnapshot.Value,
                OptionsMonitorConfiguration = _singleton.Configuration
            });
        }
    }
}

Survival-Guide/src/Mvc/Controllers/HealthController.cs
using Microsoft.AspNetCore.Mvc;
using Shared.HealthChecks;

namespace Mvc.Controllers
{
    public class HealthController : Controller
    {
        private readonly HealthCheckState _healthCheckState;

        public HealthController(HealthCheckState healthCheckState)
        {
            _healthCheckState = healthCheckState;
        }

        public IActionResult Index()
        {
            return View(_healthCheckState);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SetNotReady()
        {
            _healthCheckState.SetNotReady();

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SetReady()
        {
            _healthCheckState.SetReady();

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SetNotLive()
        {
            _healthCheckState.SetNotLive();

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SetLive()
        {
            _healthCheckState.SetLive();

            return RedirectToAction("Index");
        }
    }
}

Survival-Guide/src/Mvc/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Mvc.Models;

namespace Mvc.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Survival-Guide/src/Mvc/Controllers/VariablesController.cs
using Microsoft.AspNetCore.Mvc;

namespace Mvc.Controllers
{
    public class VariablesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Survival-Guide/src/Mvc/Views/Configuration/Index.cshtml
@model Mvc.Models.ConfigurationModel

@{
    ViewBag.Title = "Options";
    Layout = "_Layout";
}

<h2>How to manage configuration</h2>

<h3>IOptions configuration</h3>
<dl>
    <dt>City</dt>
    <dd>@Model.OptionsConfiguration.City</dd>
    <dt>Favorite mountain</dt>
    <dd>@Model.OptionsConfiguration.FavoriteMountain</dd>
</dl>

<h3>IOptionsSnapshot configuration (for transient and scoped dependencies)</h3>
<dl>
    <dt>City</dt>
    <dd>@Model.SnapshotConfiguration.City</dd>
    <dt>Favorite mountain</dt>
    <dd>@Model.SnapshotConfiguration.FavoriteMountain</dd>
</dl>

<h3>IOptionsMonitor configuration (for singleton dependencies)</h3>
<dl>
    <dt>City</dt>
    <dd>@Model.OptionsMonitorConfiguration.City</dd>
    <dt>Favorite mountain</dt>
    <dd>@Model.OptionsMonitorConfiguration.FavoriteMountain</dd>
</dl>

Survival-Guide/src/Mvc/Views/Health/Index.cshtml
@model Shared.HealthChecks.HealthCheckState

@{
    ViewBag.Title = "Health";
    Layout = "_Layout";
}

<h2>Manage readyness and liveness</h2>

<h3>Is application ready?</h3>
@if (Model.IsReady)
{
    <p>The application is ready</p>
    <form asp-area="" asp-controller="Health" , asp-action="SetNotReady">
        <button type="submit">Set not ready</button>
    </form>
}
else
{
    <p>The application is not ready</p>
    <form asp-area="" asp-controller="Health" , asp-action="SetReady">
        <button type="submit">Set ready</button>
    </form>
}

<h3>Is application live?</h3>
@if (Model.IsLive)
{
    <p>The application is live</p>
    <form asp-area="" asp-controller="Health" , asp-action="SetNotLive">
        <button type="submit">Set not live</button>
    </form>
}
else
{
    <p>The application is not ready</p>
    <form asp-area="" asp-controller="Health" , asp-action="SetLive">
        <button type="submit">Set live</button>
    </form>
}

Survival-Guide/src/Mvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Survival-Guide/src/Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mvc</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Variables" asp-action="Index">Variables</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Health" asp-action="Index">Health</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Configuration" asp-action="Index">Configuration</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Mvc
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Survival-Guide/src/Mvc/Views/Variables/Index.cshtml
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration
@model Mvc.Models.ConfigurationModel

@{
    ViewBag.Title = "Variables";
    Layout = "_Layout";
}

<h2>Configuration</h2>

<dl>
    @foreach (var entry in Configuration.AsEnumerable())
    {
        <dt>@entry.Key</dt>
        <dd>@entry.Value</dd>
    }
</dl>